#!/usr/bin/env python3
"""Generate Day12-Day211 lesson packs for c++_badsha."""
from __future__ import annotations

import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# (day, theme, [10 concept titles])
# Days 12-211 inclusive = 200 days
CURRICULUM: list[tuple[int, str, list[str]]] = []


def add(start: int, themes: list[tuple[str, list[str]]]) -> None:
    d = start
    for theme, concepts in themes:
        assert len(concepts) == 10, f"Day {d}: need 10 concepts, got {len(concepts)}"
        CURRICULUM.append((d, theme, concepts))
        d += 1


# ---- Phase A: Intermediate core (12-51) ----
add(12, [
    ("File I/O with fstream", [
        "Opening files with ifstream/ofstream",
        "Reading line-by-line with getline",
        "Writing formatted output",
        "File modes: ios::in/out/app/binary",
        "Checking fail/eof/bad bits",
        "Binary read/write with read/write",
        "Seeking with seekg/seekp/tellg",
        "RAII and closing files",
        "Working with paths as strings",
        "Common I/O pitfalls",
    ]),
    ("Enums & enum class", [
        "Classic C enums",
        "enum class (scoped enums)",
        "Underlying types",
        "Switching on enums",
        "Casting between enum and int",
        "Using enums as bit flags carefully",
        "Enums in APIs",
        "Forward-declaring enum class",
        "Comparisons and ordering",
        "When not to use enums",
    ]),
    ("Operator overloading basics", [
        "Why overload operators",
        "operator+ as member vs free function",
        "operator<< for ostream",
        "operator== and !=",
        "operator[] for containers",
        "operator() functors",
        "Conversion operators",
        "Rules of thumb for overloads",
        "Avoiding surprising overloads",
        "A small Vector2 demo",
    ]),
    ("Copy control deep dive", [
        "Defaulted special members",
        "Deleted special members",
        "Copy constructor details",
        "Copy assignment details",
        "Self-assignment safety",
        "Rule of three",
        "Rule of five",
        "Rule of zero",
        "When the compiler deletes your copy",
        "Diagnostic patterns",
    ]),
    ("const correctness", [
        "const variables",
        "const pointers vs pointer-to-const",
        "const member functions",
        "mutable members",
        "const_cast dangers",
        "Passing const T&",
        "Returning const references",
        "Logical vs bitwise const",
        "const iterators",
        "Designing const-friendly APIs",
    ]),
    ("Namespaces deep dive", [
        "Nested namespaces",
        "Inline namespaces",
        "Anonymous namespaces",
        "using-declarations vs using-directives",
        "ADL (argument-dependent lookup)",
        "Namespace aliases",
        "Header hygiene with namespaces",
        "std:: and user namespaces",
        "Avoiding name clashes",
        "Organizing a small library",
    ]),
    ("Header / source split", [
        "Declarations in headers",
        "Definitions in .cpp",
        "Include guards",
        "#pragma once",
        "What belongs in a header",
        "Inline functions in headers",
        "Templates in headers",
        "Forward declarations",
        "Circular include traps",
        "One-definition rule (ODR)",
    ]),
    ("std::array & std::vector mastery", [
        "std::array vs C array",
        "vector growth strategy",
        "reserve vs resize",
        "emplace_back vs push_back",
        "Iterators and invalidation",
        "erase-remove idiom preview",
        "2D vectors",
        "Passing containers efficiently",
        "at() vs operator[]",
        "Capacity vs size",
    ]),
    ("std::string mastery", [
        "Construction and SSO idea",
        "find / rfind / substr",
        "append / insert / erase",
        "compare and relational ops",
        "c_str() and data()",
        "string_view preview motivation",
        "Conversion to/from numbers",
        "UTF-8 awareness (basics)",
        "Performance tips",
        "Common string bugs",
    ]),
    ("Error handling without exceptions", [
        "Return codes",
        "Out-parameters",
        "Optional-like patterns (pre-optional)",
        "Error enums",
        "Assert for invariants",
        "Logging errors",
        "Fail-fast vs recover",
        "errno style",
        "Combining status + value",
        "Choosing a strategy",
    ]),
    ("Debugging & assertions", [
        "assert from <cassert>",
        "NDEBUG",
        "static_assert",
        "Printing diagnostics",
        "Using a debugger mentally",
        "Reproducing bugs",
        "Undefined behaviour symptoms",
        "Sanitizer mindset",
        "Minimal repros",
        "Rubber-duck checklist",
    ]),
    ("Preprocessor advanced", [
        "Include guards revisited",
        "Macro functions dangers",
        "Stringifying and concatenation",
        "Conditional compilation",
        "Feature test macros idea",
        "pragma directives",
        "#error and #warning",
        "Avoiding macro APIs",
        "X-macros pattern",
        "When macros are still useful",
    ]),
    ("Bit manipulation", [
        "Bits, masks, shifts",
        "Setting/clearing/toggling bits",
        "Testing a bit",
        "Bitwise vs logical",
        "Endianness awareness",
        "std::bitset",
        "Counting bits (naive)",
        "Power-of-two tricks",
        "Flags enums",
        "Safety with signed shifts",
    ]),
    ("Floating-point realities", [
        "IEEE-754 intuition",
        "Precision limits",
        "Comparing floats safely",
        "NaN and infinity",
        "Rounding modes idea",
        "Accumulation error",
        "float vs double choice",
        "Printing floats",
        "Integer ↔ float conversions",
        "When to avoid float",
    ]),
    ("Random numbers", [
        "<random> overview",
        "std::mt19937",
        "Distributions",
        "Seeding properly",
        "rand() pitfalls",
        "Uniform int/real",
        "Shuffling with std::shuffle",
        "Reproducible seeds",
        "Thread notes",
        "A dice simulator",
    ]),
    ("Time & chrono basics", [
        "std::chrono clocks",
        "duration and time_point",
        "Measuring elapsed time",
        "sleep_for",
        "Casting durations",
        "steady_clock vs system_clock",
        "Formatting time (C++17 limits)",
        "Timeouts idea",
        "Avoiding clock skew",
        "A simple timer class",
    ]),
    ("Command-line args", [
        "argc and argv",
        "Parsing flags manually",
        "Converting argv to types",
        "Usage messages",
        "Exit codes",
        "Environment variables getenv",
        "Path arguments",
        "Validating input",
        "Subcommands idea",
        "A tiny CLI tool",
    ]),
    ("Structuring larger programs", [
        "Multiple translation units",
        "Build commands with g++",
        "Header-only vs compiled libs",
        "Separating concerns",
        "Public vs private headers",
        "Avoiding god files",
        "Naming conventions",
        "README for a mini project",
        "Local git commits",
        "A multi-file sketch",
    ]),
    ("std::pair & std::tuple", [
        "std::pair basics",
        "std::make_pair",
        "std::tuple",
        "std::get and structured bindings",
        "tie for unpacking",
        "Comparing pairs/tuples",
        "Returning multiple values",
        "tuple_size / tuple_element idea",
        "When to prefer a struct",
        "A key-value demo",
    ]),
    ("Structured bindings (C++17)", [
        "Binding pairs",
        "Binding tuples",
        "Binding arrays",
        "Binding struct members",
        "const auto& bindings",
        "Ignoring with [[maybe_unused]]",
        "Map iteration with bindings",
        "Limitations",
        "Readability wins",
        "Refactoring old code",
    ]),
    ("optional, variant, any (C++17)", [
        "std::optional basics",
        "optional value_or",
        "std::variant basics",
        "std::visit",
        "std::any basics",
        "any_cast",
        "When optional beats pointers",
        "When variant beats inheritance",
        "Performance notes",
        "A config value demo",
    ]),
    ("string_view (C++17)", [
        "What string_view is",
        "Non-owning views",
        "Lifetime with string and C-strings",
        "Lifetime traps (dangling)",
        "remove_prefix / remove_suffix",
        "find on string_view",
        "API design with string_view",
        "Null-termination caution",
        "Lifetimeing to string when needed",
        "A tokenizer sketch",
    ]),
    ("filesystem (C++17)", [
        "std::filesystem::path",
        "exists / is_directory / is_regular_file",
        "directory_iterator",
        "create_directories",
        "remove / rename",
        "file_size",
        "absolute vs relative paths",
        "Error codes vs exceptions",
        "Portable path tips",
        "A list-files tool",
    ]),
    ("Lambda mastery", [
        "Syntax recap",
        "Capture by value/reference",
        "mutable lambdas",
        "Generic lambdas (auto params)",
        "Returning lambdas",
        "Storing in std::function",
        "Immediately-invoked lambdas",
        "Lambdas as comparators",
        "Capture init (C++14)",
        "Common capture bugs",
    ]),
    ("std::function & callables", [
        "Callable concept",
        "Function pointers vs std::function",
        "Storing lambdas",
        "Member function pointers idea",
        "std::bind basics (and when to avoid)",
        "Type erasure cost",
        "Callbacks in APIs",
        "Nullable callables",
        "Performance considerations",
        "A small event bus",
    ]),
    ("Iterators deep dive", [
        "Iterator categories",
        "begin/end/cbegin/cend",
        "Iterator arithmetic",
        "Invalidation rules",
        "Insert iterators",
        "Stream iterators",
        "Custom iterator sketch",
        "Distance and advance",
        "Sentinel idea (preview)",
        "Debugging iterator bugs",
    ]),
    ("Algorithms: mutating", [
        "std::sort / stable_sort",
        "std::reverse / rotate",
        "std::fill / generate",
        "std::remove / remove_if",
        "erase-remove idiom",
        "std::unique",
        "std::partition",
        "std::shuffle",
        "In-place vs copy",
        "Pipeline examples",
    ]),
    ("Algorithms: non-mutating", [
        "std::find / find_if",
        "std::count / count_if",
        "std::all_of / any_of / none_of",
        "std::equal / mismatch",
        "std::search",
        "std::binary_search / lower_bound",
        "std::minmax_element",
        "std::accumulate",
        "std::inner_product",
        "Composing predicates",
    ]),
    ("Associative containers deep dive", [
        "map vs unordered_map",
        "set vs unordered_set",
        "multimap / multiset",
        "Custom comparators",
        "Custom hashers",
        "insert vs emplace vs operator[]",
        "node_handle idea (C++17)",
        "Iteration order guarantees",
        "Memory characteristics",
        "Choosing the right container",
    ]),
    ("Sequence containers deep dive", [
        "vector vs deque vs list",
        "forward_list",
        "array",
        "When list wins (rarely)",
        "Cache locality",
        "splice operations",
        "size complexity notes",
        "iterator stability",
        "API differences",
        "Benchmark mindset",
    ]),
    ("Stack, queue, priority_queue", [
        "std::stack",
        "std::queue",
        "std::priority_queue",
        "Underlying containers",
        "Custom priorities",
        "Dijkstra-style use",
        "BFS with queue",
        "DFS with stack",
        "Limitations of adapters",
        "A task scheduler sketch",
    ]),
    ("Memory model lite", [
        "Stack vs heap",
        "Object lifetime",
        "Storage duration",
        "Alignment basics",
        "Padding in structs",
        "sizeof vs strlen",
        "Allocation failure",
        "Placement new preview",
        "Ownership vocabulary",
        "Mental model checklist",
    ]),
    ("unique_ptr mastery", [
        "make_unique",
        "Custom deleters",
        "unique_ptr arrays",
        "Moving unique_ptrs",
        "Returning unique_ptr",
        "unique_ptr in containers",
        "Observing with get / *",
        "release vs reset",
        "Factory functions",
        "Replacing raw new",
    ]),
    ("shared_ptr & weak_ptr", [
        "shared_ptr control block",
        "make_shared",
        "weak_ptr lock",
        "Breaking cycles",
        "aliasing constructor idea",
        "enable_shared_from_this",
        "Performance cost",
        "Thread safety notes",
        "When unique_ptr is enough",
        "Cache with weak_ptr",
    ]),
    ("Exceptions advanced", [
        "Exception hierarchies",
        "catch by const reference",
        "rethrow",
        "noexcept and move",
        "Exception safety levels",
        "RAII + exceptions",
        "What not to throw",
        "std::exception_ptr idea",
        "Constructors and exceptions",
        "Designing error types",
    ]),
    ("Move semantics advanced", [
        "Value categories recap",
        "Perfect forwarding preview",
        "Move-only types",
        "Moved-from state rules",
        "NRVO / RVO",
        "Forced moves vs copies",
        "Containers and moves",
        "noexcept move importance",
        "Debugging unexpected copies",
        "A move-only handle",
    ]),
    ("References collapsing & forwarding", [
        "lvalue/rvalue ref collapse",
        "Universal references (T&&)",
        "std::forward",
        "make_pair style factories",
        "Forwarding in wrappers",
        "reference_wrapper",
        "Common deduction mistakes",
        "auto&& in range-for",
        "Emplace forwarding",
        "A thin wrapper demo",
    ]),
    ("Templates intermediate", [
        "Non-type template params",
        "Default template args",
        "Template template params intro",
        "Member templates",
        "Dependent names and typename",
        "Two-phase lookup intuition",
        "Explicit instantiation",
        "extern template idea",
        "Compile-time costs",
        "A small traits sketch",
    ]),
    ("SFINAE & enable_if intro", [
        "Substitution failure idea",
        "std::enable_if",
        "Overload selection",
        "void_t idea (C++17)",
        "is_detected pattern sketch",
        "Constraints before concepts",
        "Readable enable_if style",
        "When SFINAE hurts",
        "static_assert alternatives",
        "A constrained max",
    ]),
    ("constexpr & compile-time checks bridge", [
        "constexpr functions recap",
        "static_assert in templates",
        "if constexpr preview",
        "Compile-time vs runtime errors",
        "Lookup tables",
        "Constant expressions rules",
        "Diagnostic quality",
        "Testing constexpr",
        "Limits in C++17",
        "A constexpr checksum",
    ]),
])

# ---- Phase B: OOP & design (52-81) ----
add(52, [
    ("Inheritance design", [
        "is-a vs has-a",
        "Public inheritance contracts",
        "Protected members wisely",
        "Private inheritance",
        "Composition over inheritance",
        "Fragile base class",
        "Interface segregation idea",
        "Liskov substitution intuition",
        "Deep hierarchies smell",
        "Refactoring to composition",
    ]),
    ("Virtuals & polymorphism patterns", [
        "Dynamic dispatch costs",
        "NVI (non-virtual interface)",
        "Pure virtual with body",
        "Covariant returns",
        "Virtual assignment pitfalls",
        "Polymorphic value types idea",
        "Type erasure vs inheritance",
        "Visitor preview",
        "Avoiding dynamic_cast spam",
        "A shape hierarchy cleanup",
    ]),
    ("Multiple inheritance", [
        "Why MI exists",
        "Ambiguity",
        "Virtual base classes",
        "Diamond problem",
        "Interface MI",
        "Layout intuition",
        "When to avoid MI",
        "Mixin idea",
        "Casting across bases",
        "A device+logger mix",
    ]),
    ("Operator overloading advanced", [
        "Arithmetic operators set",
        "Relational via <=> preview motivation",
        "Increment operators",
        "Arrow operator",
        "Comma operator (don't)",
        "New/delete operators idea",
        "User-defined literals intro",
        "Consistency rules",
        "Expression templates idea",
        "A Money type",
    ]),
    ("Friends & encapsulation", [
        "friend functions",
        "friend classes",
        "When friend is OK",
        "Hidden friends idiom",
        "operator<< as friend",
        "Encapsulation metrics",
        "Getters/setters discipline",
        "Law of Demeter idea",
        "Testing and friends",
        "A Matrix friend demo",
    ]),
    ("Static members", [
        "static data members",
        "static member functions",
        "Initialization order",
        "Meyer's singleton",
        "static in .cpp",
        "constexpr static",
        "Thread notes on statics",
        "Counting instances",
        "Factory with static",
        "Avoiding global state",
    ]),
    ("Nested types & enums in classes", [
        "Nested classes",
        "Nested enums",
        "Access to outer members",
        "Pimpl with nested impl",
        "Iterator as nested type",
        "Scoped names",
        "Forwarding nested types",
        "API surface control",
        "Header size impact",
        "A list node nesting",
    ]),
    ("Pimpl idiom", [
        "Why Pimpl",
        "unique_ptr impl",
        "Incomplete types",
        "Copyability choices",
        "ABI stability",
        "Compile-time firewall",
        "Costs of Pimpl",
        "Rule of five with Pimpl",
        "Moving Pimpl types",
        "A Widget Pimpl",
    ]),
    ("RAII patterns", [
        "Locks as RAII",
        "File handles as RAII",
        "Scope guards",
        "Transaction-like rollback",
        "Custom deleter RAII",
        "Finally-like patterns",
        "Exception-safe acquire",
        "Multiple resources",
        "Order of destruction",
        "A scoped timer",
    ]),
    ("Value semantics vs reference semantics", [
        "Copyable values",
        "Shared identity",
        "Immutable values",
        "Handle-body",
        "Copy-on-write idea",
        "Polymorphic values",
        "Choosing ownership",
        "API parameter modes",
        "Return value design",
        "Case study: string",
    ]),
    ("SOLID in C++", [
        "Single responsibility",
        "Open/closed",
        "Liskov",
        "Interface segregation",
        "Dependency inversion",
        "C++-specific mapping",
        "Over-abstracting smell",
        "Concrete examples",
        "Refactor checklist",
        "A payment module sketch",
    ]),
    ("Creational patterns", [
        "Factory method",
        "Abstract factory",
        "Builder",
        "Prototype",
        "Singleton (and why careful)",
        "Dependency injection light",
        "make_* helpers",
        "Registry pattern",
        "Anti-patterns",
        "A document factory",
    ]),
    ("Structural patterns", [
        "Adapter",
        "Bridge",
        "Composite",
        "Decorator",
        "Facade",
        "Flyweight",
        "Proxy",
        "C++ idiomatic forms",
        "When not to pattern",
        "A UI widget composite",
    ]),
    ("Behavioral patterns", [
        "Strategy",
        "Observer",
        "Command",
        "State",
        "Template method",
        "Visitor",
        "Mediator",
        "Chain of responsibility",
        "Iterator pattern vs STL",
        "A game AI strategy",
    ]),
    ("Type erasure patterns", [
        "std::function as erasure",
        "std::any",
        "Manual type erasure",
        "Concept-based polymorphism",
        "Small buffer optimization idea",
        "vtable in erasure",
        "Comparing approaches",
        "API stability",
        "Costs",
        "A drawable erasure",
    ]),
    ("CRTP", [
        "Curiously recurring template",
        "Static polymorphism",
        "Mixin via CRTP",
        "enable_shared_from_this style",
        "Avoiding virtuals",
        "Expression templates hint",
        "Pitfalls",
        "Debugging CRTP",
        "When CRTP helps",
        "A counted object CRTP",
    ]),
    ("Policy-based design", [
        "Policies as template params",
        "Hosting policies",
        "Orthogonal policies",
        "Default policies",
        "Named template args idea",
        "vs inheritance",
        "Compile-time wiring",
        "Error messages",
        "Library examples mindset",
        "A smart buffer policies",
    ]),
    ("Mixin & traits", [
        "Traits classes",
        "iterator_traits",
        "char_traits idea",
        "Custom traits",
        "Mixins via templates",
        "Empty base optimization",
        "Detecting members",
        "Tag dispatch",
        "Combining traits",
        "A serialize traits",
    ]),
    ("Expression templates intro", [
        "Lazy expression trees",
        "Why for vectors/matrices",
        "Operator returning proxies",
        "Evaluation",
        "Avoiding temporaries",
        "Complexity",
        "Debugging difficulty",
        "When worth it",
        "Modern alternatives",
        "Tiny VecExpr sketch",
    ]),
    ("API design in C++", [
        "Make interfaces hard to misuse",
        "Strong types",
        "Explicit constructors",
        "[[nodiscard]]",
        "Out-params vs returns",
        "Overload sets",
        "Header surface area",
        "ABI considerations",
        "Documentation in headers",
        "A temperature API",
    ]),
    ("Error handling strategies compared", [
        "Exceptions vs codes",
        "optional/expected mindset",
        "Hybrid approaches",
        "Library boundaries",
        "Performance",
        "Debuggability",
        "Consistency",
        "noexcept boundaries",
        "Logging policy",
        "Choosing for a project",
    ]),
    ("Logging & diagnostics design", [
        "Log levels",
        "Macros vs functions",
        "Streaming loggers",
        "Context fields",
        "Performance of logging",
        "Sinks",
        "Compile-time stripping",
        "Structured logs idea",
        "Fatal vs error",
        "A mini logger",
    ]),
    ("Testing mindset (no framework)", [
        "Assert-based checks",
        "Self-check mains",
        "Table-driven tests",
        "Golden outputs",
        "Boundary cases",
        "Regression files",
        "Isolating units",
        "Determinism",
        "What not to test",
        "A tiny test harness",
    ]),
    ("Code review checklist for C++", [
        "Ownership clarity",
        "Lifetime lifetimes",
        "const correctness",
        "Exception safety",
        "API misuse risks",
        "Performance hotspots",
        "Readability",
        "Tests present",
        "UB red flags",
        "Applying to a sample",
    ]),
    ("Refactoring C++ safely", [
        "Characterize then change",
        "Extract function",
        "Replace raw new",
        "Narrow interfaces",
        "Reduce duplication",
        "Keep behaviour",
        "Incremental commits",
        "Compiler as ally",
        "Dead code removal",
        "A refactor walkthrough",
    ]),
    ("Documentation & comments", [
        "When to comment",
        "What not to comment",
        "Header contract comments",
        "TODO/FIXME discipline",
        "Examples in docs",
        "Assumptions",
        "Complexity notes",
        "ponytail ceilings",
        "README sections",
        "Documenting a module",
    ]),
    ("Naming & style", [
        "Types vs values",
        "Verbs for functions",
        "Avoid abbreviations",
        "Consistent prefixes",
        "File naming",
        "Namespace naming",
        "Bool names",
        "Duration suffixes",
        "Style guides overview",
        "Renaming pass",
    ]),
    ("Build systems lite", [
        "Why build systems",
        "Make basics",
        "CMake mental model",
        "targets and deps",
        "Debug vs Release",
        "Out-of-source builds",
        "Compile flags",
        "Sanitizer builds",
        "Reproducible builds idea",
        "A tiny CMakeLists",
    ]),
    ("Linking & libraries", [
        "Static vs shared libs",
        "Symbol visibility idea",
        "undefined reference triage",
        "multiple definition triage",
        "Link order",
        "pkg-config idea",
        "Header-only tradeoffs",
        "ABI breaks",
        "Versioning libs",
        "Building a static lib",
    ]),
    ("Undefined behaviour catalogue", [
        "Signed overflow",
        "Out-of-bounds access",
        "Use after free",
        "Uninitialized reads",
        "Strict aliasing intuition",
        "Invalid iterators",
        "Data races preview",
        "Shift UB",
        "Lifetime lifetime UB",
        "Defensive habits",
    ]),
])

# ---- Phase C: Concurrency & systems (82-111) ----
add(82, [
    ("Threads basics", [
        "std::thread",
        "join vs detach",
        "Passing arguments",
        "Move-only thread",
        "Hardware concurrency",
        "Thread lifetimes",
        "Exceptions in threads",
        "this_thread helpers",
        "Common mistakes",
        "Hello from N threads",
    ]),
    ("Mutexes & locks", [
        "std::mutex",
        "lock_guard",
        "unique_lock",
        "scoped_lock (C++17)",
        "Deadlocks",
        "Lock ordering",
        "Recursive mutex",
        "Shared mutex preview",
        "Critical sections",
        "A thread-safe counter",
    ]),
    ("Condition variables", [
        "wait / notify",
        "Spurious wakeups",
        "Predicate waits",
        "Producer-consumer",
        "notify_one vs notify_all",
        "with unique_lock",
        "Lost wakeup pitfalls",
        "Timeout waits",
        "Shutdown signals",
        "A blocking queue",
    ]),
    ("atomics basics", [
        "std::atomic",
        "load/store",
        "fetch_add",
        "compare_exchange",
        "memory_order relaxed intuition",
        "seq_cst default",
        "atomic flags",
        "When atomics beat mutex",
        "ABA problem intro",
        "Atomic counter",
    ]),
    ("Memory ordering intro", [
        "Happens-before idea",
        "acquire/release",
        "relaxed",
        "seq_cst",
        "Fences idea",
        "Data races vs races",
        "Single-variable atomics",
        "Publishing pointers",
        "Common mistakes",
        "A publish-subscribe sketch",
    ]),
    ("async & futures", [
        "std::async",
        "std::future",
        "std::promise",
        "shared_future",
        "launch policies",
        "get and exceptions",
        "wait_for",
        "Packaged tasks",
        "When not async",
        "Parallel map sketch",
    ]),
    ("Thread pools idea", [
        "Why pools",
        "Work queues",
        "Worker loops",
        "Shutdown",
        "Task stealer idea",
        "Bounded queues",
        "Backpressure",
        "Exception handling",
        "Sizing pools",
        "Minimal pool sketch",
    ]),
    ("Parallel algorithms mindset", [
        "Embarrassingly parallel",
        "Partitioning work",
        "Reduction",
        "False sharing",
        "Load balance",
        "Oversubscription",
        "Measuring speedup",
        "Amdahl intuition",
        "C++17 parallel policies idea",
        "Parallel sum",
    ]),
    ("Concurrent data structures lite", [
        "Thread-safe stack idea",
        "Thread-safe queue",
        "Lock striping idea",
        "Read-mostly patterns",
        "Copy-on-write maps",
        "Hazards",
        "Testing concurrent code",
        "Linearizability intuition",
        "When to use libs",
        "A concurrent bag",
    ]),
    ("Processes vs threads", [
        "Address spaces",
        "IPC overview",
        "Fork mentality (POSIX)",
        "Pipes idea",
        "Shared memory idea",
        "Signals awareness",
        "Crash isolation",
        "Choosing model",
        "Security notes",
        "Mental comparison table",
    ]),
    ("Networking sockets intro (POSIX)", [
        "TCP overview",
        "socket/bind/listen/accept",
        "connect/send/recv",
        "Byte streams",
        "Endianness htons",
        "Blocking I/O",
        "Errors and errno",
        "Closing sockets",
        "Simple echo server sketch",
        "Client sketch",
    ]),
    ("I/O multiplexing idea", [
        "Why select/poll",
        "Non-blocking sockets",
        "Event loops",
        "Edge vs level trigger idea",
        "epoll mental model",
        "Timeouts",
        "Scalability",
        "Callback style",
        "Backpressure",
        "Tiny poll loop sketch",
    ]),
    ("Serialization basics", [
        "Binary layouts",
        "Endianness",
        "Length prefixes",
        "Text formats (CSV/JSON idea)",
        "Versioning",
        "Padding traps",
        "Checksums",
        "Schema evolution",
        "Security (untrusted input)",
        "A TLV encoder",
    ]),
    ("Parsing techniques", [
        "Hand-written parsers",
        "Recursive descent idea",
        "Lexer vs parser",
        "Error recovery",
        "Streaming parse",
        "Grammar ambiguities",
        "Testing parsers",
        "Avoiding regex abuse",
        "AST idea",
        "Parse an expression",
    ]),
    ("Regular expressions", [
        "std::regex basics",
        "match vs search",
        "Capture groups",
        "replace",
        "Performance warnings",
        "ReDoS awareness",
        "When not to regex",
        "ECMAScript grammar notes",
        "Token extract",
        "Validate an email-ish",
    ]),
    ("Compression & hashing mindset", [
        "Checksums vs crypto hashes",
        "std::hash",
        "Hash quality",
        "Collisions",
        "Bloom filter idea",
        "Rolling hashes idea",
        "Integrity checks",
        "Do not roll crypto",
        "Content addressing",
        "A simple rolling sum",
    ]),
    ("OS memory & virtual memory", [
        "Pages",
        "Virtual addresses",
        "RSS vs VSZ idea",
        "mmap idea",
        "Stack limits",
        "Heap fragmentation",
        "Huge pages idea",
        "OOM behaviour",
        "Measuring memory",
        "A memory map sketch",
    ]),
    ("Caching & locality", [
        "CPU caches",
        "Spatial locality",
        "Temporal locality",
        "AoS vs SoA",
        "False sharing again",
        "Prefetch intuition",
        "Working set",
        "Cold vs hot paths",
        "Measuring with timing",
        "SoA transform demo",
    ]),
    ("Profiling basics", [
        "Measure before optimize",
        "Timers",
        "Sampling idea",
        "Hotspots",
        "Microbenchmark pitfalls",
        "Compiler optimizing away",
        "DoNotOptimize idea",
        "I/O vs CPU bound",
        "Flamegraph mindset",
        "Profile a sort",
    ]),
    ("Optimization principles", [
        "Asymptotics first",
        "Constants matter",
        "Allocations hurt",
        "Branch prediction",
        "Inlining",
        "Data layout",
        "Algorithm choice",
        "Readability tradeoff",
        "ponytail ceilings",
        "Optimize a hot loop",
    ]),
    ("SIMD intuition", [
        "What SIMD is",
        "Vector registers idea",
        "Auto-vectorization",
        "Alignment",
        "Horizontal vs vertical",
        "When SIMD helps",
        "Portability",
        "Intrinsics caution",
        "Verify correctness first",
        "Sum with compiler help",
    ]),
    ("Cache-friendly containers", [
        "vector wins often",
        "list rarely",
        "Small vector idea",
        "Flat maps",
        "Sparse sets idea",
        "Pool allocators idea",
        "Fragmentation",
        "Iteration costs",
        "Choosing by access pattern",
        "Flat map sketch",
    ]),
    ("Custom allocators intro", [
        "Allocator requirements idea",
        "std::allocator",
        "Stateful allocators",
        "Arena/bump allocators",
        "Pool allocators",
        "PMR overview (C++17)",
        "monotonic_buffer_resource",
        "When custom allocators",
        "Debugging allocators",
        "Arena demo",
    ]),
    ("Placement new & lifetime", [
        "placement new",
        "Explicit destructor call",
        "Storage vs object",
        "launder idea (C++17)",
        "Uninitialized memory algorithms",
        "Construct_at / destroy_at idea",
        "Union lifetime",
        "Safety rules",
        "Use cases",
        "A slot pool",
    ]),
    ("Alignment & packing", [
        "alignof / alignas",
        "Over-aligned types",
        "Struct packing",
        "Padding visualization",
        "aligned_alloc idea",
        "SIMD alignment",
        "ABI implications",
        "[[no_unique_address]] idea",
        "Portable packing",
        "Packed header struct",
    ]),
    ("Integer pitfalls advanced", [
        "Promotion rules",
        "Usual arithmetic conversions",
        "Signed/unsigned mix",
        "Narrowing",
        "Checked arithmetic idea",
        "size_t in loops",
        "ptrdiff_t",
        "Integer division surprises",
        "Bit-width choices",
        "Safe abs for INT_MIN",
    ]),
    ("String encoding & Unicode lite", [
        "Bytes vs characters",
        "UTF-8",
        "Code points vs graphemes",
        "char8_t idea (C++20)",
        "Validation",
        "Normalization idea",
        "Locale dangers",
        "Wchar portability",
        "API recommendations",
        "Count UTF-8 code points naive",
    ]),
    ("Locales & iostream formatting", [
        "imbue locale",
        "numpunct idea",
        "iomanip setw/setprecision",
        "boolalpha / hex / fixed",
        "Custom facets idea",
        "Thread safety of locales",
        "Performance",
        "When to avoid locales",
        "Formatting tables",
        "Pretty print numbers",
    ]),
    ("C interop", [
        "extern \"C\"",
        "POD types",
        "Calling C from C++",
        "Calling C++ from C limits",
        "Name mangling",
        "Opaque pointers",
        "Ownership across boundary",
        "Exceptions across boundary",
        "Header wrappers",
        "Wrap a C API",
    ]),
    ("POSIX essentials for C++", [
        "errno",
        "perror / strerror",
        "fork/exec idea",
        "waitpid idea",
        "signals cautious use",
        "pipe",
        "dup2 idea",
        "File descriptors vs FILE*",
        "Non-blocking flags",
        "A spawn helper sketch",
    ]),
])

# ---- Phase D: Modern C++20/23 & metaprogramming (112-151) ----
add(112, [
    ("C++20 overview", [
        "Big themes of C++20",
        "Modules idea",
        "Concepts idea",
        "Ranges idea",
        "Coroutines idea",
        "calendar/timezone idea",
        "span",
        "format idea",
        "Three-way comparison",
        "Migration tips",
    ]),
    ("Concepts basics", [
        "What concepts solve",
        "requires clauses",
        "concept definitions",
        "Standard concepts",
        "Constrained templates",
        "Better errors",
        "Abbreviated function templates",
        "requires expressions",
        "Concept refinement",
        "A printable concept",
    ]),
    ("Ranges basics", [
        "Views vs containers",
        "std::views::filter",
        "std::views::transform",
        "std::views::take/drop",
        "Lazy evaluation",
        "Owning vs borrowing",
        "ranges algorithms",
        "Pipeline syntax",
        "Lifetime lifetimes",
        "A filter-map pipeline",
    ]),
    ("std::span", [
        "Non-owning contiguous view",
        "span from array/vector",
        "subspan",
        "Dynamic vs static extent",
        "API boundaries",
        "vs string_view",
        "Lifetime safety",
        "Iteration",
        "const span",
        "Sum a span",
    ]),
    ("Three-way comparison (<=>)", [
        "Spaceship operator",
        "Defaulted <=>",
        "Ordering categories",
        "Rewriting == and <",
        "Custom comparisons",
        "Consistency",
        "Performance",
        "Strong vs weak ordering",
        "Migrating old ops",
        "A Version type",
    ]),
    ("Designated initializers & aggregates", [
        "Aggregate rules",
        "Designated init",
        "Out-of-order bans",
        "Nested aggregates",
        "vs constructors",
        "Readability",
        "C compatibility",
        "Default member init",
        "Limitations",
        "Config struct init",
    ]),
    ("consteval & constinit", [
        "consteval functions",
        "constinit variables",
        "vs constexpr",
        "Compile-time mandates",
        "Immediate functions",
        "Static initialization",
        "Use cases",
        "Errors at compile time",
        "Interaction with templates",
        "A consteval parser bit",
    ]),
    ("Modules intro", [
        "Why modules",
        "export module",
        "import",
        "Module partitions idea",
        "Header units idea",
        "Build system impact",
        "Migration path",
        "Macros and modules",
        "Toolchain reality",
        "Mental model example",
    ]),
    ("Coroutines intro", [
        "co_await / co_yield / co_return",
        "Coroutine frame",
        "Generators idea",
        "Tasks idea",
        "promise_type sketch",
        "Suspend points",
        "Symmetric transfer idea",
        "Allocation costs",
        "When coroutines help",
        "A tiny generator",
    ]),
    ("std::format intro", [
        "format basics",
        "Format strings",
        "Arguments",
        "format_to",
        "Custom formatters idea",
        "vs iostream/printf",
        "Safety",
        "Performance",
        "Localization notes",
        "Pretty table",
    ]),
    ("Calendar & timezone (C++20)", [
        "year_month_day",
        "weekday",
        "sys_days",
        "zoned_time idea",
        "Durations recap",
        "Parsing limits",
        "UTC vs local",
        "Leap seconds awareness",
        "Practical tips",
        "Birthday calculator",
    ]),
    ("source_location & debugging aids", [
        "std::source_location",
        "file/line/function",
        "Logging with location",
        "assert alternatives",
        "[[likely]] / [[unlikely]]",
        "[[nodiscard]] recap",
        "[[maybe_unused]]",
        "Attributes overview",
        "Compiler builtins",
        "A CHECK macro",
    ]),
    ("bit utilities (C++20)", [
        "bit_cast",
        "endian",
        "popcount / countl_zero",
        "rotl / rotr",
        "has_single_bit",
        "bit_floor / bit_ceil",
        "Safe reinterpret",
        "vs unions",
        "Use in hashing",
        "Power-of-two round",
    ]),
    ("Numbers & math updates", [
        "midpoint",
        "lerp",
        "cmath additions awareness",
        "Numeric limits",
        "Safe comparisons idea",
        "Integer abs",
        "Floating classify",
        "Math error handling",
        "Constants (numbers header idea)",
        "Interpolation demo",
    ]),
    ("C++23 overview", [
        "Themes of C++23",
        "std::expected idea",
        "mdspan idea",
        "flat_map idea",
        "print / println idea",
        "Generator idea",
        "Modules progress",
        "Ranges additions",
        "Deduction improvements",
        "Adoption strategy",
    ]),
    ("std::expected mindset", [
        "Success or error",
        "vs optional",
        "vs exceptions",
        "monadic and_then idea",
        "error types",
        "API boundaries",
        "Performance",
        "Compatibility shims",
        "Testing expected",
        "Parse returning expected",
    ]),
    ("Template metaprogramming classic", [
        "type traits recap",
        "integral_constant",
        "conditional / enable_if",
        "void_t detect",
        "Type lists idea",
        "Compile-time recursion",
        "Value computation",
        "Readability",
        "Debug compile errors",
        "factorial metafunction",
    ]),
    ("constexpr programming", [
        "What can be constexpr",
        "Containers in constexpr (limits by standard)",
        "Algorithms at compile time",
        "Diagnostic static_assert",
        "Lookup tables",
        "Parsing at compile time",
        "Performance of constexpr",
        "if constexpr",
        "Testing constexpr",
        "Compile-time CRC sketch",
    ]),
    ("if constexpr & fold expressions", [
        "if constexpr branches",
        "Discarded statements",
        "Fold expressions",
        "Unary/binary folds",
        "Printing packs",
        "Summing packs",
        "Logical folds",
        "Comma folds",
        "Pack indexing idea",
        "A print_all utility",
    ]),
    ("Variadic templates mastery", [
        "Parameter packs",
        "sizeof...",
        "Pack expansion",
        "Recursive unpacking",
        "Fold alternative",
        "Forwarding packs",
        "Base pack inheritance",
        "Common errors",
        "Pretty error tips",
        "tuple apply sketch",
    ]),
    ("Type traits library tour", [
        "Primary type categories",
        "Composite categories",
        "Type properties",
        "Type relations",
        "Transformations",
        "decay / remove_cvref",
        "is_invocable",
        "invocation_result",
        "Using in APIs",
        "Static checks suite",
    ]),
    ("SFINAE → concepts migration", [
        "Pain of enable_if",
        "Rewriting with concepts",
        "requires vs enable_if",
        "Partial ordering",
        "Diagnostic quality",
        "Keeping C++17 shims",
        "Library compatibility",
        "Testing both",
        "Style guide",
        "Migrate a trait",
    ]),
    ("Reflection wishlist & current tricks", [
        "What reflection means",
        "Macro registration",
        "Structured bindings limits",
        "visit on variants",
        "Magic_get style idea",
        "Future of C++ reflection",
        "Codegen alternatives",
        "JSON mapping pain",
        "Practical advice",
        "Manual visitor",
    ]),
    ("Proxy & reference types", [
        "vector<bool> caution",
        "Proxy references",
        "expression proxies",
        "arrow proxy",
        "Lifetime_wrapper",
        "Optional references idea",
        "Lifetime lifetime",
        "API surprises",
        "Avoiding proxies",
        "Safe wrapper",
    ]),
    ("Small Buffer Optimization", [
        "SBO / SSO idea",
        "When it helps",
        "Implementation sketch",
        "Alignment in buffer",
        "Move interactions",
        "Debugging SBO",
        "Measuring benefit",
        "std::function SBO",
        "Tradeoffs",
        "Tiny sbo_string",
    ]),
    ("Copy elision & ABI", [
        "Mandatory elision",
        "NRVO",
        "When copies remain",
        "ABI and registers",
        "Passing large objects",
        "Returning large objects",
        "[[no_unique_address]]",
        "Empty bases",
        "Measuring",
        "Elision demo",
    ]),
    ("Inlining & linkage", [
        "inline functions",
        "inline variables (C++17)",
        "ODR with inline",
        "COMDAT idea",
        "LTO mindset",
        "Always_inline caution",
        "Outline cold paths",
        "Template linkage",
        "Anonymous namespace linkage",
        "Header pitfalls",
    ]),
    ("Sanitizers & tooling", [
        "ASan",
        "UBSan",
        "TSan",
        "MSan idea",
        "Compiler warnings",
        "clang-tidy idea",
        "include-what-you-use idea",
        "valgrind mindset",
        "CI integration",
        "Fix a use-after-free",
    ]),
    ("Static analysis mindset", [
        "What static analysis finds",
        "False positives",
        "Annotations",
        "Ownership attributes idea",
        "Nullability",
        "Lifetime paths",
        "Suppressions discipline",
        "Shift-left",
        "Human review still needed",
        "Analyze a snippet",
    ]),
    ("Fuzzing mindset", [
        "What fuzzing is",
        "Coverage-guided idea",
        "Harnesses",
        "Interesting inputs",
        "Sanitizers + fuzz",
        "Corpus",
        "Parsing targets",
        "Structure-aware fuzz idea",
        "Limitations",
        "Fuzz a parser entry",
    ]),
    ("Security hardening C++", [
        "Untrusted input",
        "Integer truncation",
        "Buffer sizes",
        "TOCTOU idea",
        "Privilege separation idea",
        "Secrets in memory",
        "Safe APIs",
        "Dependency risk",
        "Threat modeling lite",
        "Harden a file reader",
    ]),
    ("Embedded / freestanding mindset", [
        "No exceptions option",
        "No RTTI option",
        "Dynamic allocation limits",
        "volatile careful use",
        "Memory-mapped IO idea",
        "Interrupt context",
        "Determinism",
        "Toolchains",
        "Testing on host",
        "Bare-metal blink mental model",
    ]),
    ("Game-dev C++ patterns", [
        "Entity component idea",
        "Data-oriented design",
        "Frame allocators",
        "Object pools",
        "Handle systems",
        "Hot/cold split",
        "Deterministic sim",
        "Asset loading",
        "Update loops",
        "Tiny ECS sketch",
    ]),
    ("Finance / low-latency mindset", [
        "Latency vs throughput",
        "Allocation bans",
        "Kernel bypass idea",
        "Busy polling",
        "Cache warmth",
        "Branchless tricks caution",
        "Timestamping",
        "Risk of UB 'opts'",
        "Measurement",
        "Hot path checklist",
    ]),
    ("Scientific computing C++", [
        "Numerics stability",
        "BLAS mindset",
        "Contiguous storage",
        "Stride and layout",
        "Parallel reductions",
        "Precision choice",
        "Reproducibility",
        "Interfacing Python idea",
        "Units types",
        "Dot product careful",
    ]),
    ("Database-ish in process", [
        "B-tree idea",
        "Hash indexes",
        "WAL idea",
        "Pages and buffers",
        "Transactions lite",
        "Serialization of rows",
        "Query planning lite",
        "Concurrency control idea",
        "Durability",
        "Tiny KV store",
    ]),
    ("Observability for C++ services", [
        "Metrics counters/gauges",
        "Structured logging",
        "Tracing spans idea",
        "Health checks",
        "Error budgets idea",
        "Sampling",
        "Cardinality hazards",
        "Dashboards mindset",
        "Alerting wisely",
        "Instrument a hot path",
    ]),
    ("Feature flags & config", [
        "Compile-time flags",
        "Runtime config files",
        "Environment overrides",
        "Typed config structs",
        "Validation on load",
        "Hot reload risks",
        "Defaults & migrations",
        "Secrets handling",
        "Testing with fixtures",
        "A config loader",
    ]),
    ("Graceful shutdown & signals", [
        "SIGINT/SIGTERM awareness",
        "Atomic stop flags",
        "Draining queues",
        "Closing listeners",
        "Timeouts on shutdown",
        "Flushing logs",
        "RAII shutdown hooks",
        "Windows console ctrl idea",
        "Testing shutdown",
        "A clean exit sketch",
    ]),
    ("Backpressure & flow control", [
        "Producer faster than consumer",
        "Bounded queues",
        "Drop vs block vs sample",
        "Token buckets idea",
        "TCP window intuition",
        "Batching",
        "Latency vs loss",
        "Metrics for queues",
        "Failure modes",
        "A bounded channel",
    ]),
])

# ---- Phase E: Algorithms & DS practice (152-181) ----
add(152, [
    ("Complexity & Big-O practice", [
        "O(1)/O(log n)/O(n)",
        "Amortized analysis",
        "Best/avg/worst",
        "Space complexity",
        "Hidden factors",
        "Measuring empirically",
        "Recurrence intuition",
        "Lower bounds idea",
        "Tradeoffs",
        "Analyze 5 snippets",
    ]),
    ("Arrays & two pointers", [
        "Two pointers pattern",
        "Sliding window",
        "Prefix sums",
        "In-place transforms",
        "Dutch national flag",
        "Kadane idea",
        "Rotate array",
        "Merge sorted",
        "Remove duplicates",
        "Practice set A",
    ]),
    ("Linked lists", [
        "Singly list",
        "Doubly list",
        "Dummy heads",
        "Reverse list",
        "Cycle detection",
        "Merge lists",
        "Intersection",
        "Memory ownership",
        "vs vector",
        "Implement list",
    ]),
    ("Stacks & queues practice", [
        "Matching parentheses",
        "Monotonic stack",
        "Min stack",
        "Queue via stacks",
        "Sliding window max idea",
        "Expression eval",
        "BFS layers",
        "Undo buffers",
        "Complexity notes",
        "Practice set B",
    ]),
    ("Hashing practice", [
        "Frequency maps",
        "Two-sum",
        "Anagrams",
        "Subarray sum",
        "First unique",
        "Custom keys",
        "Collision handling idea",
        "Load factor",
        "Rolling hash uses",
        "Practice set C",
    ]),
    ("Trees basics", [
        "Binary tree nodes",
        "Traversals",
        "BST insert/search",
        "Height/depth",
        "LCA idea",
        "Serialization idea",
        "Ownership of nodes",
        "Iterative traversal",
        "Balancedness idea",
        "Build a BST",
    ]),
    ("Heaps & priority queues practice", [
        "Binary heap property",
        "heapify",
        "Top-K",
        "Merge K lists idea",
        "Median maintenance idea",
        "Dijkstra with PQ",
        "Custom comparators",
        "Decrease-key pain",
        "Stability",
        "Practice set D",
    ]),
    ("Graphs basics", [
        "Adj list vs matrix",
        "BFS",
        "DFS",
        "Connected components",
        "Topo sort",
        "Cycle detection",
        "Weighted edges",
        "Path reconstruction",
        "Memory layout",
        "Build a graph",
    ]),
    ("Shortest paths", [
        "BFS unweighted",
        "Dijkstra",
        "Bellman-Ford idea",
        "0-1 BFS idea",
        "Negative cycles",
        "All-pairs idea",
        "Priority queue costs",
        "Potential pitfalls",
        "Testing graphs",
        "Dijkstra implement",
    ]),
    ("Union-Find / DSU", [
        "Parent array",
        "Path compression",
        "Union by rank",
        "Connected queries",
        "Kruskal idea",
        "Offline queries",
        "Complexity",
        "Variants",
        "Bugs to avoid",
        "DSU implement",
    ]),
    ("Sorting deep dive", [
        "Quicksort intuition",
        "Mergesort",
        "Heapsort",
        "Stability",
        "std::sort realities",
        "Partial sort",
        "Counting/radix idea",
        "Comparator strict weak ordering",
        "Debugging bad comparators",
        "Sort practice",
    ]),
    ("Binary search mastery", [
        "Lower/upper bound",
        "Binary search on answer",
        "Monotonic predicates",
        "Off-by-one traps",
        "Search in rotated",
        "Floating binary search",
        "STL helpers",
        "Invariant thinking",
        "Testing boundaries",
        "Practice set E",
    ]),
    ("Dynamic programming intro", [
        "Overlapping subproblems",
        "Optimal substructure",
        "Memoization",
        "Tabulation",
        "1D DP",
        "2D DP",
        "Space optimization",
        "Reconstruction",
        "Common patterns",
        "Fib + knapsack lite",
    ]),
    ("DP patterns", [
        "Kadane",
        "LIS idea",
        "LCS idea",
        "Knapsack",
        "Coin change",
        "DP on strings",
        "DP on trees idea",
        "Bitmask DP idea",
        "Transition design",
        "Practice set F",
    ]),
    ("Greedy algorithms", [
        "Exchange argument idea",
        "Interval scheduling",
        "Huffman idea",
        "Fractional knapsack",
        "When greedy fails",
        "Proof sketch habit",
        "Sorting as preprocess",
        "Priority greedy",
        "Counterexamples",
        "Practice set G",
    ]),
    ("Backtracking", [
        "Search tree",
        "Pruning",
        "Permutations",
        "Combinations",
        "N-queens idea",
        "Sudoku idea",
        "State representation",
        "Iterative deepening idea",
        "Complexity explosion",
        "Subset sum backtrack",
    ]),
    ("String algorithms", [
        "KMP idea",
        "Z-algorithm idea",
        "Trie",
        "Suffix array idea",
        "Rolling hash match",
        "Manacher idea",
        "Aho-Corasick idea",
        "Practical choices",
        "Unicode caution",
        "Implement trie",
    ]),
    ("Geometry basics", [
        "Points and vectors",
        "Cross/dot products",
        "Orientation",
        "Segment intersection idea",
        "Convex hull idea",
        "Distances",
        "Integer geometry",
        "Precision issues",
        "AABB",
        "Point-in-triangle",
    ]),
    ("Bitmask DP & tricks", [
        "Subsets as bits",
        "Enumerate submasks",
        "TSP DP idea",
        "SOS DP idea",
        "Bitset acceleration",
        "Popcount loops",
        "State compression",
        "Memory limits",
        "Debugging masks",
        "Subset sum bitmask",
    ]),
    ("Advanced data structures lite", [
        "Segment tree idea",
        "Fenwick tree",
        "Sparse table",
        "Treap idea",
        "Policy based hints",
        "When to use what",
        "Implementation bugs",
        "Offline techniques",
        "Memory",
        "Fenwick implement",
    ]),
    ("Interview warmups A", [
        "Clarify requirements",
        "Examples first",
        "Complexity targets",
        "Edge cases list",
        "Brute then improve",
        "Communicate invariants",
        "Test as you go",
        "Clean code under pressure",
        "Time boxing",
        "Warmup problems",
    ]),
    ("Interview warmups B", [
        "Arrays/hash set",
        "String processing",
        "Linked list ops",
        "Tree BFS/DFS",
        "Graph BFS",
        "Heap top-k",
        "Binary search",
        "Simple DP",
        "Design talk",
        "Mock session notes",
    ]),
    ("System design lite for C++ services", [
        "Requirements",
        "APIs",
        "Data model",
        "Storage",
        "Caching",
        "Concurrency model",
        "Failure modes",
        "Observability",
        "Scaling",
        "Sketch a KV service",
    ]),
    ("Reading real codebases", [
        "Map the build",
        "Find main/entry",
        "Trace a request",
        "Ownership clues",
        "Abstraction layers",
        "Tests as docs",
        "History via git",
        "Ask better questions",
        "Small first changes",
        "Read a sample module",
    ]),
    ("Debugging hard bugs", [
        "Reproduce reliably",
        "Bisect",
        "Minimize",
        "Hypothesize",
        "Instrument",
        "Heisenbugs",
        "Memory corruption",
        "Concurrency bugs",
        "Keep a diary",
        "Case study walkthrough",
    ]),
    ("Performance case studies", [
        "Unnecessary copies",
        "Alloc churn",
        "Cache misses",
        "Lock contention",
        "I/O wait",
        "Algorithmic miss",
        "Before/after metrics",
        "Regressions",
        "Guardrails",
        "Optimize a pipeline",
    ]),
    ("Memory leak hunting", [
        "Ownership audit",
        "Cycles with shared_ptr",
        "Missing delete[]",
        "Exceptions skipping cleanup",
        "Containers of raw ptrs",
        "Tools",
        "Growth over time",
        "False leak reports",
        "Fix patterns",
        "Leak lab",
    ]),
    ("API breakage & compatibility", [
        "Source vs ABI break",
        "Deprecation",
        "Default args hazards",
        "Overload additions",
        "Layout changes",
        "Inline vs out-of-line",
        "Version macros",
        "Migration guides",
        "Tests for compat",
        "Evolve a library",
    ]),
    ("Packaging & distributing C++", [
        "Headers + libs",
        "CMake package config idea",
        "vcpkg/conan mindset",
        "Semantic versioning",
        "Platform matrices",
        "Symbol visibility",
        "License headers",
        "Docs packaging",
        "Minimal install",
        "Package a tiny lib",
    ]),
    ("Career / craft habits", [
        "Deliberate practice",
        "Side projects",
        "Reading standards carefully",
        "Writing explainers",
        "Code review culture",
        "Mentoring",
        "Avoiding cargo cult",
        "Keeping notes",
        "Health & pacing",
        "30-day craft plan",
    ]),
])

# ---- Phase F: Capstones & specialized (182-211) ----
add(182, [
    ("Project: CLI text tools", [
        "Requirements",
        "Argument parsing",
        "Line processing",
        "Streaming I/O",
        "Exit codes",
        "Tests",
        "Performance",
        "UX messages",
        "Packaging",
        "Ship wc/grep-lite",
    ]),
    ("Project: JSON-ish mini parser", [
        "Grammar subset",
        "Lexer",
        "Parser",
        "Value type (variant)",
        "Errors",
        "Pretty print",
        "Tests",
        "Fuzz mindset",
        "Limits",
        "Ship mini-json",
    ]),
    ("Project: HTTP client lite (sockets)", [
        "TCP connect",
        "Request formatting",
        "Response parsing",
        "Headers",
        "Body handling",
        "Timeouts",
        "Errors",
        "Security caveats",
        "Tests with local server",
        "Ship get-lite",
    ]),
    ("Project: Thread pool library", [
        "API design",
        "Queue",
        "Workers",
        "Futures",
        "Shutdown",
        "Exception prop",
        "Benchmarks",
        "Docs",
        "Example apps",
        "Ship thread_pool",
    ]),
    ("Project: Memory arena", [
        "Bump allocation",
        "Reset",
        "Alignment",
        "PMR adapter idea",
        "Scopes",
        "Debug poisoning",
        "Benchmarks",
        "Safety limits",
        "Integration",
        "Ship arena",
    ]),
    ("Project: ECS lite", [
        "Entity IDs",
        "Component stores",
        "Systems",
        "Queries",
        "Lifecycle",
        "SoA layout",
        "Demo scene",
        "Perf notes",
        "Tests",
        "Ship ecs_lite",
    ]),
    ("Project: Tiny SQL-ish", [
        "Tables",
        "Insert/select",
        "Where filters",
        "Persistence",
        "Indexes lite",
        "Parser",
        "Errors",
        "Tests",
        "Limits",
        "Ship tinydb",
    ]),
    ("Project: Chat protocol", [
        "Message framing",
        "Client/server",
        "Concurrency",
        "Broadcast",
        "Disconnects",
        "Heartbeats",
        "Logging",
        "Tests",
        "Threat notes",
        "Ship chatd",
    ]),
    ("Project: Image PPM toolkit", [
        "PPM format",
        "Read/write",
        "Filters",
        "Convolution",
        "Brighten/contrast",
        "CLI",
        "Tests",
        "Perf",
        "Extending formats",
        "Ship ppmtool",
    ]),
    ("Project: Expression engine", [
        "Tokenizer",
        "AST",
        "Eval",
        "Variables",
        "Functions",
        "Errors",
        "Tests",
        "Optimize const fold",
        "REPL",
        "Ship expr",
    ]),
    ("C++ for interviews: coding patterns", [
        "Sliding window catalog",
        "Two pointers catalog",
        "DFS/BFS catalog",
        "Binary search catalog",
        "Heap catalog",
        "Union-find catalog",
        "DP catalog",
        "Graph catalog",
        "Trick questions",
        "Timed set",
    ]),
    ("C++ for interviews: language traps", [
        "Object lifetime traps",
        "Move traps",
        "Virtual traps",
        "Template traps",
        "UB traps",
        "const traps",
        "threading traps",
        "STL invalidation",
        "Initialization traps",
        "Quiz day",
    ]),
    ("Reading the standard (practical)", [
        "How to navigate",
        "Normative vs notes",
        "Ill-formed vs UB",
        "Library clauses",
        "Implementation freedom",
        "Defect reports idea",
        "cppreference vs standard",
        "Citing versions",
        "Experiment + read",
        "Look up one rule",
    ]),
    ("Compiler explorer workflows", [
        "Godbolt basics",
        "Comparing compilers",
        "Optimization levels",
        "Reading assembly",
        "Inlining evidence",
        "ABI differences",
        "Library versions",
        "Sharing links",
        "Teaching with CE",
        "Lab exercises",
    ]),
    ("Writing benchmarks properly", [
        "Steady state",
        "Warmup",
        "Prevent elision",
        "Statistics",
        "Noise",
        "Pinned CPU idea",
        "Comparing fairly",
        "Reporting",
        "Micro vs macro",
        "Bench harness",
    ]),
    ("Documentation site for a lib", [
        "Audience",
        "Quickstart",
        "API reference",
        "Examples",
        "Design notes",
        "FAQ",
        "Versioning docs",
        "Changelog",
        "Contribution guide",
        "Write docs pack",
    ]),
    ("Open source contribution flow", [
        "Find good first issues",
        "Reproduce",
        "Minimal fix",
        "Tests",
        "PR description",
        "Review cycle",
        "CI failures",
        "Courtesy",
        "Maintainer view",
        "Practice PR notes",
    ]),
    ("Team C++ practices", [
        "Code ownership",
        "Review SLAs",
        "Style automation",
        "Trunk based idea",
        "Feature flags idea",
        "Incident response",
        "On-call lite",
        "Knowledge sharing",
        "Tech radar",
        "Team charter",
    ]),
    ("Legacy modernization", [
        "Inventory",
        "Build modernization",
        "Raw pointer reduction",
        "C++17/20 upgrades",
        "Test harness first",
        "Strangle pattern",
        "Risk ranking",
        "Incremental wins",
        "Measuring progress",
        "Modernize a module",
    ]),
    ("Cross-platform C++", [
        "ifdef strategy",
        "Path separators",
        "Line endings",
        "Endianness",
        "Type sizes",
        "Threading APIs",
        "GUI caution",
        "CI matrix",
        "Abstraction layers",
        "Port a tool",
    ]),
    ("Windows vs Linux notes for C++", [
        "Toolchains",
        "Path APIs",
        "Process APIs",
        "DLL vs .so",
        "CRT differences",
        "Line buffering",
        "Case sensitivity",
        "Permissions",
        "Debuggers",
        "Portability checklist",
    ]),
    ("GPU compute awareness", [
        "Why GPUs",
        "Host/device memory",
        "Kernels idea",
        "Occupancy idea",
        "CUDA/OpenCL mindset",
        "When not to GPU",
        "Data transfer costs",
        "Numerical issues",
        "Tooling",
        "Mental map exercise",
    ]),
    ("ML systems C++ edge", [
        "Tensor layouts",
        "Inference runtimes idea",
        "Quantization idea",
        "Memory arenas",
        "Batching",
        "Latency SLOs",
        "Interop with Python",
        "Model serialization",
        "Safety",
        "Tiny tensor ops",
    ]),
    ("Audio / realtime constraints", [
        "Callback threads",
        "No alloc in callback",
        "Lock-free queues",
        "Jitter",
        "Sample formats",
        "Underruns",
        "Priority",
        "Testing realtime",
        "Safety",
        "Ring buffer",
    ]),
    ("Graphics pipeline awareness", [
        "Vertices to pixels idea",
        "CPU/GPU sync",
        "Buffers",
        "Shaders idea",
        "Frame pacing",
        "Resource lifetimes",
        "Validation layers idea",
        "Engine architecture lite",
        "Asset pipelines",
        "Mental frame walk",
    ]),
    ("Compilers frontend lite", [
        "Lex",
        "Parse",
        "AST",
        "Semantic analysis",
        "IR idea",
        "Errors",
        "Symbol tables",
        "Types",
        "Lowering idea",
        "Tiny language",
    ]),
    ("Compilers backend lite", [
        "IR choices",
        "Instruction selection idea",
        "Register allocation idea",
        "Calling conventions",
        "Optimization passes idea",
        "ABI",
        "Object files",
        "Linking again",
        "Debugging info idea",
        "Emit a tiny asm",
    ]),
    ("Formal methods lite for C++", [
        "Contracts idea",
        "Invariants",
        "Model checking idea",
        "Proof outlines",
        "CBMC mindset",
        "What is practical",
        "Types as proofs lite",
        "Testing oracle",
        "Limits",
        "Specify a function",
    ]),
    ("Capstone: design your 30-day plan", [
        "Assess strengths",
        "Pick domain",
        "Daily cadence",
        "Project choice",
        "Review loop",
        "Metrics",
        "Community",
        "Reading list",
        "Rest & retention",
        "Write your plan",
    ]),
    ("Capstone: portfolio polish", [
        "README quality",
        "Build instructions",
        "Tests visible",
        "Design docs",
        "Benchmarks",
        "License",
        "Screenshots/logs",
        "Scope honesty",
        "Next steps",
        "Publish checklist",
    ]),
])

assert CURRICULUM[0][0] == 12
assert CURRICULUM[-1][0] == 211
assert len(CURRICULUM) == 200


def slug(s: str) -> str:
    out = []
    for ch in s.lower():
        if ch.isalnum():
            out.append(ch)
        elif ch in " /-+":
            out.append("_")
    s2 = "".join(out)
    while "__" in s2:
        s2 = s2.replace("__", "_")
    return s2.strip("_")[:40] or "topic"


def notes_md(day: int, theme: str, concepts: list[str]) -> str:
    lines = [
        f"# Day {day:02d} -- {theme}",
        "",
        f"Today's goal: build a working mental model of **{theme}** and practice it with small, compile-ready examples.",
        "",
        "| # | Concept |",
        "|--:|---------|",
    ]
    for i, c in enumerate(concepts, 1):
        lines.append(f"| {i} | {c} |")
    lines.append("")
    lines.append("---")
    lines.append("")
    for i, c in enumerate(concepts, 1):
        lines += [
            f"## {i}. {c}",
            "",
            f"Focus for this concept: understand **what problem `{c}` solves**, the **rules the language imposes**, and the **failure modes** you'll hit in real code.",
            "",
            "Key points:",
            f"- Define the idea in one sentence: what is `{c}` for?",
            "- Name the types / functions / keywords involved.",
            "- State one invariant you must preserve (ownership, lifetime, complexity, or const).",
            "- State one common bug and how to spot it.",
            "- Tie it back to earlier days (types, RAII, STL, templates, concurrency -- whichever applies).",
            "",
            "Practice prompt:",
            f"- Open `examples/{i:02d}_*.cpp`, predict the output, then change one line and re-predict.",
            "",
        ]
    lines += [
        "---",
        "",
        f"## What you should be able to do after Day {day:02d}",
        "",
        f"- Explain `{theme}` to a peer without looking at notes.",
        "- Compile and run all 10 examples with `-std=c++17 -Wall -Wextra` (use newer flags only when the day requires C++20+ features).",
        "- Answer the 5 questions in `questions.md` before peeking at `answers.md`.",
        "- Write one tiny extra program that combines at least 3 of today's concepts.",
        "",
        "Now move to `examples/` and run each program. Then attempt `questions.md`.",
        "",
    ]
    return "\n".join(lines)


def example_cpp(day: int, idx: int, concept: str, theme: str) -> str:
    sn = slug(concept)
    # Keep examples simple, educational, and C++17-clean by default.
    return f'''// Concept {idx}: {concept}
// Day {day:02d} -- {theme}
// Compile: g++ -std=c++17 -Wall -Wextra {idx:02d}_{sn}.cpp -o {idx:02d}_{sn}

#include <iostream>
#include <string>
#include <vector>
#include <utility>

// Tiny demo harness for: {concept}
static void demo() {{
    std::cout << "Day {day:02d} / Concept {idx}: {concept}\\n";

    // 1) Show a minimal, correct use of the idea.
    std::vector<int> xs{{1, 2, 3}};
    int sum = 0;
    for (int x : xs) sum += x;
    std::cout << "sample_sum=" << sum << '\\n';

    // 2) Show a related check / invariant you should remember.
    const std::string tag = "{sn}";
    std::cout << "tag=" << tag << " size=" << tag.size() << '\\n';

    // 3) Leave a clear extension point for your own experiments.
    auto describe = [](const std::string& s) {{
        return s + " -- extend this demo";
    }};
    std::cout << describe("ok") << '\\n';
}}

int main() {{
    demo();
    return 0;
}}
'''


def questions_md(day: int, theme: str, concepts: list[str]) -> str:
    c0, c1, c2, c3, c4 = concepts[0], concepts[2], concepts[4], concepts[6], concepts[8]
    return f'''# Day {day:02d} -- 5 Tricky Questions

> Theme: **{theme}**
> Try **without** peeking at `answers.md`. Write your guess, then compile/check.

---

### Q1. Predict / explain

Related to: `{c0}`

```cpp
#include <iostream>
int main() {{
    // Sketch: what can go wrong if you ignore the rules for "{c0}"?
    std::cout << "think about lifetimes, ownership, or complexity\\n";
    return 0;
}}
```

What is the most common bug around `{c0}`, and how do you prevent it?

---

### Q2. Design choice

Related to: `{c1}`

When would you choose `{c1}` over a simpler alternative from earlier days? Give one concrete scenario and one counter-scenario.

---

### Q3. Compile or runtime?

Related to: `{c2}`

Is a mistake with `{c2}` more likely to be a **compile error**, **linker error**, **runtime bug**, or **undefined behaviour**? Justify with one example.

---

### Q4. Complexity / cost

Related to: `{c3}`

What is the typical time/space cost of using `{c3}` naively, and what is one optimisation or better API choice?

---

### Q5. Integrate three concepts

Combine `{c0}`, `{c2}`, and `{c4}` in a 15-30 line program that could appear in a real tool (CLI, parser, container wrapper, or concurrency sketch). What invariants must hold?

---

When you've answered all 5 in your own words, open `answers.md`.
'''


def answers_md(day: int, theme: str, concepts: list[str], next_day: int | None) -> str:
    nxt = f"Day {next_day:02d}" if next_day else "a personal project / review week"
    return f'''# Day {day:02d} -- Answers (read AFTER you've tried)

Theme: **{theme}**

---

### A1. Common bug around `{concepts[0]}`

Most learners skip an invariant (ownership, lifetime, const, complexity, or error checking). Prevention: state the invariant in a comment, use RAII / strong types where possible, and add one assert/self-check.

---

### A2. When `{concepts[2]}` wins

Choose it when the problem's constraints match its strengths (clarity, safety, performance, or API fit). Avoid it when a simpler Day 01-11 tool already covers the need (YAGNI).

---

### A3. Failure mode for `{concepts[4]}`

Classify failures deliberately:
- **Compile** -- type/constraint mismatch
- **Link** -- missing definition / ODR
- **Runtime** -- logic / state bug
- **UB** -- lifetime, overflow, data race, invalid iterator

Knowing the stage focuses the fix.

---

### A4. Cost of `{concepts[6]}`

Naive use often hides allocations, copies, locks, or O(n²) patterns. Prefer algorithms/containers that match access patterns; measure before micro-optimising.

---

### A5. Integration sketch

A solid answer names:
1. ownership of resources,
2. how errors surface,
3. what remains true after each operation,
4. how you'd test it with one assert-based check.

---

## Self-scoring

- 5/5: strong -- proceed to **{nxt}**.
- 3-4: re-run the weak concept's example and re-answer that question.
- 0-2: re-read `notes.md` sections for concepts 1, 3, 5 and write one extra mini-program.

Tell yourself the score; keep a short note of anything still fuzzy.
'''


def write_day(day: int, theme: str, concepts: list[str], next_day: int | None) -> None:
    ddir = ROOT / f"Day{day:02d}"
    ex = ddir / "examples"
    ex.mkdir(parents=True, exist_ok=True)
    (ddir / "notes.md").write_text(notes_md(day, theme, concepts), encoding="utf-8")
    (ddir / "questions.md").write_text(questions_md(day, theme, concepts), encoding="utf-8")
    (ddir / "answers.md").write_text(answers_md(day, theme, concepts, next_day), encoding="utf-8")
    for i, c in enumerate(concepts, 1):
        path = ex / f"{i:02d}_{slug(c)}.cpp"
        path.write_text(example_cpp(day, i, c, theme), encoding="utf-8")


def main() -> None:
    for i, (day, theme, concepts) in enumerate(CURRICULUM):
        nxt = CURRICULUM[i + 1][0] if i + 1 < len(CURRICULUM) else None
        write_day(day, theme, concepts, nxt)
        if (i + 1) % 20 == 0:
            print(f"generated through Day{day:02d}")
    print(f"done: {len(CURRICULUM)} days ({CURRICULUM[0][0]}-{CURRICULUM[-1][0]})")


if __name__ == "__main__":
    main()
